### ISSUE TITLE
Should we add organization and people?

### ISSUE THREAD

**Issue by aloisdg** [d-edge/foss-acronyms#1]
Hello,

I wonder whether we should add organization like the FSF (Free Software Foundation) and the OSI (Open Source Initiative) and famous FOSS people like RMS (Richard Matthew Stallman) and ESR (Eric S. Raymond).

Cheers,

**Comment by boehs** [comment]
Yes to orgs, no to people

**Comment by aloisdg** [comment]
Alright let's do that for now.
