### ISSUE TITLE
Add CLI

### ISSUE THREAD

**Issue by aloisdg** [d-edge/foss-acronyms#100]
Hello,

It would be nice to add CLI for command-line interface https://en.wikipedia.org/wiki/Command-line_interface

Cheers

**Comment by caio-bernardo** [comment]
Hello there! Can the CLI be written in any language? And all what the cli needs to do, is return the results for a given acronym?

**Comment by aloisdg** [comment]
I was looking to add the "CLI" acronyms to the json, but the idea of a cli app to print acronym is a great idea too!

**Comment by aloisdg** [comment]
No problem I like the idea of a cli app though. I am all for building one. Keep in touch 👍
