### ISSUE TITLE
PEBCAK definition is for PEBKAC

### ISSUE THREAD

**Issue by adipurnamk** [d-edge/foss-acronyms#106]
Hello
I just discovered that the definition of PEBCAK was swapped for PEBKAC, which has been cross-checked from this [source](https://en.wikipedia.org/wiki/User_error).

Is it possible for me to fix it and add some variant of PEBCAK? even though it means the same

**Comment by aloisdg** [comment]
Hello,

It seems that both are used: [PEBKAC](https://github.com/orgs/community/discussions/25165#discussioncomment-3246690) and [PEBCAK](https://github.com/Humanizr/Humanizer/issues/1157#issue-1086741428).

For discoverability purpose, I think we should add all of them. Go for it :)

**Comment by adipurnamk** [comment]
Thank you @aloisdg for assigning me this task.
:)
