### ISSUE TITLE
Add RFP and RFI

### ISSUE THREAD

**Issue by aloisdg** [d-edge/foss-acronyms#11]
Hello,

> you may want to add RFP - Request for Proposal, and RFI - Request for Information.

as suggested by [/u/pconwell](https://www.reddit.com/r/github/comments/qpel7q/on_github_i_faced_a_lot_of_acronyms_i_made_a_list/hjuwl4x/?context=3)

example for [RFP](https://github.com/fnplus/join-fnplus-with-a-pr#request-for-proposals) and [RFI](https://github.com/python/request-for/blob/master/2019-Q1-PyPI/RFI.md)

If you want to solve this issue, check this [how-to guide](https://github.com/d-edge/foss-acronyms/blob/main/CONTRIBUTING.md#add-new-acronym).

**Comment by mateuseap** [comment]
Can you assign this issue to me? I'll work on it :)

**Comment by mateuseap** [comment]
I made one PR and added the acronyms referred to this issue and issue #25! If that's not okay, I can redo these issues in separated PRs

**Comment by aloisdg** [comment]
And it is merged! Ty
