### ISSUE TITLE
Add GAT

### ISSUE THREAD

**Issue by aloisdg** [d-edge/foss-acronyms#129]
GATs (generic associated types) https://blog.rust-lang.org/2021/08/03/GATs-stabilization-push.html https://old.reddit.com/r/rust/comments/ynvm8a/could_someone_explain_the_gats_like_i_was_5/

**Comment by KatShulu** [comment]
Je veux bien prendre celle la s'il te plait

**Comment by aloisdg** [comment]
Yes
