### ISSUE TITLE
[meme] Can anyone else relate? 

### ISSUE THREAD

**Issue by aloisdg** [d-edge/foss-acronyms#13]
![image](https://user-images.githubusercontent.com/3449303/142724140-0f59300a-7da7-4cc7-af23-8102bc6991c0.png)

[source](https://www.reddit.com/r/ProgrammerHumor/comments/qxobd6/can_anyone_else_relate/)

**Comment by iamrahulrnair** [comment]
Hey, I Added description for DRY in my forked repo, I cant seems to find that changes here, could you check on that

**Comment by iamrahulrnair** [comment]
Yeah its kind of funny, I will try to add some more expansions 🙂
