### ISSUE TITLE
Add KPI

### ISSUE THREAD

**Issue by nadhell** [d-edge/foss-acronyms#130]
KPI (Key Performance Indicator) https://www.klipfolio.com/resources/articles/what-is-a-key-performance-indicator https://www.qlik.com/us/kpi

**Comment by nadhell** [comment]
Hello, 
Can I be assigned this issue please ?
Have a nice day !

**Comment by torendil** [comment]
Yes, go ahead!

**Comment by nadhell** [comment]
Thank you, I'm on it !
