### ISSUE TITLE
Add SE/SWE/SRE

### ISSUE THREAD

**Issue by aloisdg** [d-edge/foss-acronyms#23]
Hi!

We can three more:

SE: Software Engineer or System Engineer
SWE: SoftWare Engineer
SRE: Site Reliability Engineer

Thank you

**Comment by ArshdeepSingh98** [comment]
Hi, I have created a pull request for this issue. Please review and merge. Thanks!

**Comment by aloisdg** [comment]
and it is merged! thanks again :+1:
