### ISSUE TITLE
Add POCO and POJO

### ISSUE THREAD

**Issue by aloisdg** [d-edge/foss-acronyms#28]
Hello,

It would be nice to add POCO for Plain Of C# Object.

[example](https://github.com/d-edge/Diffract#example-outputs)

Thank you!

**Comment by Tarmil** [comment]
And equivalents in other languages: https://en.wikipedia.org/wiki/Plain_old_Java_object

**Comment by aloisdg** [comment]
Let's add both1

**Comment by Alexluu13** [comment]
Add POCO and POJO

**Comment by aloisdg** [comment]
@Alexluu13 sure :) Waiting for your PR! :+1:

**Comment by aloisdg** [comment]
I unassigned it because someone else did it too and we did not have any news. No problem though. Feel free to tackle another issue :)
