### ISSUE TITLE
Links are not rendered as markdown

### ISSUE THREAD

**Issue by aloisdg** [d-edge/foss-acronyms#35]
![image](https://user-images.githubusercontent.com/3449303/152361327-7e62118c-677b-461b-9758-184cbc0ac2e1.png)

**Comment by mcanever** [comment]
I noticed the same and the GitHub action we're using doesn't seem to render markdown inside the table cells. They're using
https://github.com/a-x-/table-builder for building the table but that library doesn't seem to be aware of markdown...
Do you prefer putting HTML in the JSON or maybe find a way to generate Markdown from the JSON instead? (I'm assuming that github gets confused by the mix of HTML and markdown in the md file

**Comment by aloisdg** [comment]
I used HTML in JSON. I thought about using one more GH Action to render the MD to HTML, but ending using a regex instead. I think it would be better to have a way to template inside a cell

**Comment by mcanever** [comment]
Makes sense. If I find some spare time I may think of forking the github action to take a template for the link cell of the table
