### ISSUE TITLE
Add TFA and DAG

### ISSUE THREAD

**Issue by aloisdg** [d-edge/foss-acronyms#55]
> TFA is "The Fine Article"; essentially this HN submission. DAG is "Directed Acyclic Graph"; a graph with directed edges and no cycles.

[source](https://news.ycombinator.com/item?id=31805834)

**Comment by Kerrick** [comment]
Originally "TFA" actually stood for "The F*cking Article" but "Fine" is a bit family-friendlier.

**Comment by aloisdg** [comment]
RTFA/TFA would be added under Read The Fine Article / The Fine Article

**Comment by aloisdg** [comment]
A different PR can be made for DAG
