### ISSUE TITLE
Add DI/DIP

### ISSUE THREAD

**Issue by aloisdg** [d-edge/foss-acronyms#59]
Hello,

It would be nice to DI/DIP for Dependency Inversion Principle

Example:
https://github.com/dwmkerr/hacker-laws#the-dependency-inversion-principle=

**Comment by ArshdeepSingh98** [comment]
I would like to add this one.

**Comment by ArshdeepSingh98** [comment]
I have created a PR for this. Please take a look at it. Thanks!
