### ISSUE TITLE
Add MVC and MVVM

### ISSUE THREAD

**Issue by aloisdg** [d-edge/foss-acronyms#93]
Since we just merged MVC (cf #92) we could also add other design patterns like MVP and MVVM.

Note that we already have an entry for MVP (i.e. Most Valuable Product).

While we should be able to have both, I think we could group those design patterns together.

**Comment by Sensational-Code** [comment]
I added MVVM in #96, but by grouping MVP together do you mean having 2 definitions for the entry of MVP, or do you mean having 2 entries for MVP with different definitions next to the other design patterns? Or did you mean having an entirely new acronym section for design patterns?

**Comment by aloisdg** [comment]
I was thinking abut adding a new section for design patterns (i.e. a group for MVC, MVP, MVVM).
I even started it [design-patterns.json](https://github.com/d-edge/foss-acronyms/blob/main/data/design-patterns.json), but I found a bug and I am working on it first.
